[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

;==== 原生USB CDC核心开关 ====
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

upload_protocol = esptool
upload_speed = 921600

;自动识别端口，不用硬写COM号
upload_port = auto
board_upload.wait_for_upload_port = false

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
