[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2@^1.6.9

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
